In [13]:
import numpy as np

In [14]:
max_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(max_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [19]:
mx_1s.dtype

dtype('float64')

In [20]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
mx_0s = np.zeros((3,4), dtype = int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
mx_0s = np.zeros((3,4), dtype = bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [25]:
mx_0s = np.zeros((3,4), dtype = str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [26]:
em_str = ''
print(bool(em_str))

False


In [28]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 1.075e-320]
 [0.000e+000 0.000e+000 0.000e+000]]
