In [91]:
#random sampling with numpy

In [92]:
import numpy as np
import random

In [93]:
np.random.random(1)

array([0.97150578])

In [94]:
np.random.random((3,3))

array([[0.02417593, 0.56716739, 0.62109938],
       [0.51130855, 0.03798847, 0.59075472],
       [0.40034462, 0.9497373 , 0.92792582]])

In [95]:
np.random.randint(1,4)

3

In [96]:
np.random.randint(1,4, (4,4))

array([[2, 3, 1, 3],
       [1, 3, 3, 3],
       [2, 1, 3, 3],
       [3, 1, 1, 3]])

In [98]:
np.random.randint(1,4, (2,4,4))

array([[[3, 2, 1, 1],
        [2, 3, 3, 3],
        [2, 2, 2, 1],
        [1, 1, 2, 2]],

       [[3, 1, 3, 2],
        [1, 3, 3, 3],
        [3, 3, 3, 2],
        [2, 1, 1, 2]]])

In [100]:
np.random.seed(10)
#seed function is use to use same array every time which random function genrated
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [101]:
np.random.seed(10)
#seed function is use to use same array every time which random function genrated
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [102]:
2**32 -1

4294967295

In [103]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [104]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [105]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [106]:
x = [1,2,3,4]
np.random.choice(x)

1

In [107]:
x = [1,2,3,4]
np.random.choice(x)

1

In [109]:
for i in range(20):
    print(np.random.choice(x))

1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3


In [111]:
np.random.permutation(x)


array([2, 3, 4, 1])

In [112]:
np.random.permutation(x)

array([1, 4, 2, 3])