In [1]:
import numpy as np

In [2]:
#np.arange(star,End, steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [5]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [7]:
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
ar9 = ar.flatten(order = 'C')
print(ar9)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
ar9 = ar.flatten(order = 'F')
print(ar9)

[ 1  7  2  8  3  9  4 10  5 11  6 12]


In [20]:
ar9 = ar.flatten(order = 'A')
print(ar9)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
ar9 = ar.flatten(order = 'K')
print(ar9)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
ar8 = ar.transpose()
print(ar8)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
